# Generated by Django 6.0.6 on 2026-06-11 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_landlordprofile_tenantprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantprofile',
            name='monthly_income',
        ),
    ]
