# Generated by Django 6.0.6 on 2026-06-22 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_tenantprofile_monthly_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlordprofile',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='landlordprofile',
            name='business_registration_number',
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='employer_name',
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='employment_status',
        ),
    ]
