# Generated by Django 6.0.6 on 2026-06-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('bedsitter', 'Bedsitter'), ('commercial', 'Commercial')], default='apartment', max_length=20),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('apartment_unit', 'Apartment Unit'), ('villa', 'Villa'), ('townhouse', 'Townhouse'), ('bedsitter', 'Bedsitter'), ('office', 'Office'), ('shop', 'Shop')], max_length=20, null=True),
        ),
    ]
