# Generated by Django 6.0.6 on 2026-07-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_property_type_unit_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
