# Generated by Django 6.0.6 on 2026-06-24 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0002_alter_lease_unit'),
        ('properties', '0002_property_property_type_unit_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='properties.unit'),
        ),
    ]
